[package]
name = "seph"
version.workspace = true
edition.workspace = true

[features]

[dependencies]
common = { path = "../nvim-common" }

serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
