[package]
name = "fs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-fs = { workspace = true }
e31e = { workspace = true }
futures-util = { workspace = true }

[lints]
workspace = true
