[package]
name = "walkdir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nvimx2 = { workspace = true }

[lints]
workspace = true
